version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/budget_app_db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: budget_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

